* Qcircuits

Qcircuits is a tool for designing quantum experiments using
abstractions that can be translated in different ways to real life
experiments, and compare what results should be expected for those
experiments under different hypotheses, with special emphasis in
deterministic hypotheses.

By deterministic hypotheses, we mean hypotheses in which all the
randomness for each particle is set in the source, but there's no
randomness in the transformations that the different filters
(detectors) in the experiment may apply to each particle.

A deterministic hypothesis can be equivalent to a non deterministic one for some experiments but not all.

* Introduction

In our abstraction, in each experiment we have a source of particles
which are thrown to a filter, in which the particle is determined to
go to one of the filter's 2 possible exists. Those exits can in turn
point to other filters.  One exit could even point to a previous
filter for which the particle has already passed through
(recursion). In real experiments this can presumably be implemented
with mirrors.  Each filter selects for one of 2 apparent (abstract)
properties of particles: color (Black or White) and harness (Hard,
Soft).

Let's see some examples for induction of the rules this system works by:

Example 1:
#+BEGIN_SRC
Source--|Color|--Black--|Color|--Black--detector(50%)
              |               |--White--detector(0%)
              |
              |--White--|Color|--Black--detector(0%)
                              |--White--detector(50%)
#+END_SRC

Example 2 is just like example 1 but with Harness instead of Color:
#+BEGIN_SRC
Source--|Harness|--Hard--|Harness|--Hard--detector(50%)
                |                |--Soft--detector(0%)
                |
                |--Soft--|Harness|--Hard--detector(0%)
                                 |--Soft--detector(50%)
#+END_SRC

These two examples seems to indicate that once you have
detected/selected to be of one color or harness by some filter, the
color or harness seems to persist,

Example 3:
#+BEGIN_SRC
Source--|Color|--Black--|Harness|--Soft--detector(25%)
              |                 |--Hard--detector(25%)
              |
              |--White--|Harness|--Soft--detector(25%)
                                |--Hard--detector(25%)
#+END_SRC

Example 4 is just like example 3 but in reverse:

#+BEGIN_SRC
Source--|Harness|--Soft--|Color|--Black--detector(25%)
                |              |--White--detector(25%)
                |
                |--Hard--|Color|--Black--detector(25%)
                               |--White--detector(25%)
#+END_SRC

These two examples seem to indicate color and harness are independent from each other.

Example 5:
#+BEGIN_SRC
Source--|Color|--Black--|Harness|--Soft--|Color|--Black--detector(12.5%)
              |                 |              |--White--detector(12.5%)
              |                 |--Hard--|Color|--Black--detector(12.5%)
              |                                |--White--detector(12.5%)
              |--White--|Harness|--Soft--|Color|--Black--detector(12.5%)
                                |              |--White--detector(12.5%)
                                |--Hard--|Color|--Black--detector(12.5%)
                                               |--White--detector(12.5%)
#+END_SRC

Example 6 is just like example 5 but in reverse and it's left to the reader to complete as an exercise.

This is where things get interesting it seems that measuring the
harness somehow "resets" the color that was previously filtered for
(and vice versa). You can combine the two types of sensors in
different ways and the same effect will be observed.

* Change in notation

Instead of using Color (Black, White) and Harness (Hard, Soft) filters,
we will be using Vertical (Left, Right) and Horizontal filters. This
abstraction that seems more intuitive for the properties observed,
since it seemingly a particle can only be in one of the 4 states at
once, like an orientation.

This way we can also not be concerned about being accused of discriminating particles by color. Or harness.

* Questions

** Question 1

Q: Can we produce a deterministic hypothesis that reproduces all the examples above?

A: Yes. It's already implemented.

** Question 2:

Q: Considering examples 5 and 6 a tree of depth of 3, how deep can this project go with a deterministic hypothesis?

A: Depth 6.

** Question 3:

Q: If we knew the maximum depth of the deepest experiment that's going
to be done, can we produce a deterministic hypothesis that will
satisfy out conditions?

A: I think it should be obvious that the answer is yes, but I haven't proven it yet.
It's also quite likely I'm just missing something about quantum mechanics.

** Question 4:

Q: what is the maximum depth that has been tried in real life experiments?

TODO I don't know.

** Question 5:

Q: Can we produce deterministic hypotheses that are seemingly equivalent to the non deterministic ones?
In other words: Can the randomness be set from the beginning for each particle and the filters be purely deterministic?
In other words, can we get to depth=infinity with a deterministic hypothesis?

A: I think not. No matter how big is the state of the particle, if the
number of final exits is bigger than the cardinality of the state,
that is, the total number of possible initial states, then two
particles with the same initial state will unavoidably come out of the
same final exit, leaving some exits empty.

There's probably some other mathematical proof of this, I've been told there is.
TODO find and link to the mathematical proof.

But if we can produce a deterministic hypothesis for any depth that
has been tried and will ever be tried, then the following claim can
never be falsified using the scientific method:
"A deterministic model exists to explain any seemingly non deterministic observations".

In fact, infinite models exist equivalent to any model of any universe
we can think of, deterministic or not. But for now that's beyond the
scope of this project.

Please, somebody tell me where I'm wrong.

* References

** MIT 8.04 Quantum Physics I, Spring 2013 (2013)

This introductory video on quantum physics may help to make sense of this project:

https://www.youtube.com/watch?v=lZ3bPUKo5zc
